"""add goal to task

Revision ID: 1337c763f5d2
Revises: e549ce44660b
Create Date: 2025-11-05 01:20:04.108772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1337c763f5d2'
down_revision = 'e549ce44660b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
