"""Recreate model migrations

Revision ID: e549ce44660b
Revises: 9aa90a30ad5e
Create Date: 2025-11-01 23:19:53.745986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e549ce44660b'
down_revision = '9aa90a30ad5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('completed_at',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('completed_at',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
